### ISSUE TITLE
Some wrong and missing keys

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce-language-admin#2]
en-GB.com_jce.ini

The key 'WF_OPTION_PASTETEXT' does not match the key 'WF_OPTION_PASTE_TEXT' in the file \components\com_jce\editor\tiny_mce\plugins\clipboard\clipboard.xml

Missing keys: WF_STYLES_TEXT_FONT_DESC, WF_STYLES_TEXT_SIZE_DESC, WF_STYLES_TEXT_WEIGHT_DESC, WF_MEDIABOX_ATTRIBUTE, WF_MEDIABOX_ATTRIBUTE_DESC and some keys from the file \components\com_jce\editor\tiny_mce\plugins\xhtmlxtras\tmpl\standard_html5.php.

**Comment by ryandemmer** [comment]
The title attributes have been remove in commit - https://github.com/widgetfactory/jce/commit/f733254a4d679ae1951d6639176ac4be3a9b3d19
